name = 'Ankidoc'
license = 'MIT'
licenselink = 'https://github.com/tifrueh/hugo-ankidoc/blob/main/LICENSE'
description = 'Theme for ankidoc displaying websites.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/tifrueh/hugo-ankidoc'

# If you have a running demo of the theme
demosite = 'https://ankidoc.tifrueh.ch'

# If the theme has a single author
[author]
  name = 'Timo Früh'
  homepage = 'https://www.tifrueh.ch'
